development:
  api_key: 3a767a6f1903e1c5f30ab4748d49bf06
  password: 9e875a1eaea506c293b2d66ad034a3c5
  theme_id: 154317959
  store: eightcig-2.myshopify.com
  bucket_size: 40
  refill_rate: 2
  concurrency: 2
  whitelist_files:
  - layout/
  - assets/
  - config/
  - snippets/
  - templates/
  - locales/